version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - php
  php:
    image: php:8.1-fpm
    volumes:
      - ./:/var/www
    working_dir: /var/www
